import type { Question } from "@shared/schema";

export const QUESTIONS: Question[] = [
  // Section 1: Profil de Base (10 questions)
  { id: "sexe", sectionId: "profil-base", type: "radio", label: "Tu es ?", options: [{ value: "homme", label: "Homme" }, { value: "femme", label: "Femme" }], required: true },
  { id: "prenom", sectionId: "profil-base", type: "text", label: "Quel est ton prénom ?", placeholder: "Ex: Marc, Sophie...", required: true },
  { id: "age", sectionId: "profil-base", type: "number", label: "Quel est ton age ?", placeholder: "Ex: 32", min: 15, max: 99, required: true },
  { id: "taille", sectionId: "profil-base", type: "number", label: "Quelle est ta taille (cm) ?", placeholder: "Ex: 175", min: 140, max: 220, unit: "cm", required: true },
  { id: "poids", sectionId: "profil-base", type: "number", label: "Quel est ton poids actuel (kg) ?", placeholder: "Ex: 78", min: 40, max: 200, unit: "kg", required: true },
  { id: "objectif", sectionId: "profil-base", type: "select", label: "Quel est ton objectif principal ?", options: [{ value: "perte-graisse", label: "Perte de graisse" }, { value: "prise-muscle", label: "Prise de muscle" }, { value: "performance", label: "Performance sportive" }, { value: "sante", label: "Sante generale" }, { value: "energie", label: "Plus d'energie" }, { value: "recomposition", label: "Recomposition corporelle" }], required: true },
  { id: "profession", sectionId: "profil-base", type: "select", label: "Quel type de travail fais-tu ?", options: [{ value: "bureau", label: "Travail de bureau" }, { value: "terrain", label: "Travail de terrain/physique" }, { value: "mixte", label: "Mixte bureau/terrain" }, { value: "teletravail", label: "Teletravail" }, { value: "etudiant", label: "Etudiant" }, { value: "autre", label: "Autre" }] },
  { id: "niveau-activite", sectionId: "profil-base", type: "select", label: "Quel est ton niveau d'activite quotidienne ?", options: [{ value: "sedentaire", label: "Sedentaire (bureau)" }, { value: "leger", label: "Legerement actif" }, { value: "modere", label: "Moderement actif" }, { value: "actif", label: "Tres actif" }, { value: "intense", label: "Extremement actif" }], required: true },
  { id: "historique-medical", sectionId: "profil-base", type: "checkbox", label: "As-tu des antecedents medicaux ?", options: [{ value: "diabete", label: "Diabete" }, { value: "hypertension", label: "Hypertension" }, { value: "cholesterol", label: "Cholesterol" }, { value: "thyroide", label: "Problemes thyroidiens" }, { value: "cardiaque", label: "Problemes cardiaques" }, { value: "aucun", label: "Aucun" }] },
  { id: "medicaments", sectionId: "profil-base", type: "select", label: "Prends-tu des medicaments actuellement ?", options: [{ value: "non", label: "Non" }, { value: "occasionnel", label: "Occasionnellement" }, { value: "quotidien", label: "Quotidiennement" }] },
  { id: "allergies", sectionId: "profil-base", type: "checkbox", label: "As-tu des allergies alimentaires ?", options: [{ value: "gluten", label: "Gluten" }, { value: "lactose", label: "Lactose" }, { value: "fruits-coque", label: "Fruits a coque" }, { value: "oeufs", label: "Oeufs" }, { value: "crustaces", label: "Crustaces" }, { value: "aucune", label: "Aucune" }] },

  // Section 2: Composition Corporelle (8 questions - tour taille/hanches supprimees car analysees via photos)
  { id: "masse-grasse", sectionId: "composition-corporelle", type: "select", label: "Estime ton pourcentage de masse grasse", options: [{ value: "10-15", label: "10-15% (tres sec)" }, { value: "16-20", label: "16-20% (athletique)" }, { value: "21-25", label: "21-25% (moyen)" }, { value: "26-30", label: "26-30% (leger surplus)" }, { value: "30+", label: "Plus de 30%" }, { value: "inconnu", label: "Je ne sais pas" }] },
  { id: "objectif-poids", sectionId: "composition-corporelle", type: "select", label: "Combien de kilos voudrais-tu perdre/prendre ?", options: [{ value: "perdre-10+", label: "Perdre plus de 10 kg" }, { value: "perdre-5-10", label: "Perdre 5-10 kg" }, { value: "perdre-1-5", label: "Perdre 1-5 kg" }, { value: "maintenir", label: "Maintenir mon poids" }, { value: "prendre-1-5", label: "Prendre 1-5 kg" }, { value: "prendre-5+", label: "Prendre plus de 5 kg" }] },
  { id: "evolution-poids", sectionId: "composition-corporelle", type: "select", label: "Comment a evolue ton poids ces 6 derniers mois ?", options: [{ value: "stable", label: "Stable" }, { value: "perte", label: "Perte de poids" }, { value: "gain", label: "Prise de poids" }, { value: "yoyo", label: "Effet yoyo" }] },
  { id: "regimes-passes", sectionId: "composition-corporelle", type: "select", label: "Combien de regimes as-tu essaye ?", options: [{ value: "0", label: "Aucun" }, { value: "1-2", label: "1-2 regimes" }, { value: "3-5", label: "3-5 regimes" }, { value: "5+", label: "Plus de 5" }] },
  { id: "morphologie", sectionId: "composition-corporelle", type: "select", label: "Quel est ton type morphologique ?", options: [{ value: "ectomorphe", label: "Ectomorphe (mince, difficulte a prendre)" }, { value: "mesomorphe", label: "Mesomorphe (athletique naturellement)" }, { value: "endomorphe", label: "Endomorphe (tendance a stocker)" }] },
  { id: "zones-stockage", sectionId: "composition-corporelle", type: "checkbox", label: "Ou stockes-tu principalement ?", options: [{ value: "ventre", label: "Ventre" }, { value: "hanches", label: "Hanches" }, { value: "cuisses", label: "Cuisses" }, { value: "bras", label: "Bras" }, { value: "dos", label: "Dos" }, { value: "partout", label: "Uniformement" }] },
  { id: "retention-eau", sectionId: "composition-corporelle", type: "select", label: "Souffres-tu de retention d'eau ?", options: [{ value: "jamais", label: "Jamais" }, { value: "parfois", label: "Parfois" }, { value: "souvent", label: "Souvent" }, { value: "toujours", label: "Toujours" }] },
  { id: "cellulite", sectionId: "composition-corporelle", type: "select", label: "Presence de cellulite ?", options: [{ value: "aucune", label: "Aucune" }, { value: "legere", label: "Legere" }, { value: "moderee", label: "Moderee" }, { value: "importante", label: "Importante" }] },

  // Section 3: Metabolisme & Energie (10 questions)
  { id: "niveau-energie-matin", sectionId: "metabolisme-energie", type: "select", label: "Quel est ton niveau d'energie le matin ?", options: [{ value: "tres-bas", label: "Tres bas (epuise)" }, { value: "bas", label: "Bas" }, { value: "moyen", label: "Moyen" }, { value: "bon", label: "Bon" }, { value: "excellent", label: "Excellent" }] },
  { id: "niveau-energie-aprem", sectionId: "metabolisme-energie", type: "select", label: "Quel est ton niveau d'energie l'apres-midi ?", options: [{ value: "tres-bas", label: "Tres bas" }, { value: "bas", label: "Bas" }, { value: "moyen", label: "Moyen" }, { value: "bon", label: "Bon" }, { value: "excellent", label: "Excellent" }] },
  { id: "niveau-energie-soir", sectionId: "metabolisme-energie", type: "select", label: "Quel est ton niveau d'energie le soir ?", options: [{ value: "tres-bas", label: "Tres bas" }, { value: "bas", label: "Bas" }, { value: "moyen", label: "Moyen" }, { value: "bon", label: "Bon" }, { value: "excellent", label: "Excellent" }] },
  { id: "coup-fatigue", sectionId: "metabolisme-energie", type: "select", label: "As-tu des coups de fatigue ?", options: [{ value: "jamais", label: "Jamais" }, { value: "parfois", label: "Parfois" }, { value: "souvent", label: "Souvent" }, { value: "toujours", label: "Toujours" }] },
  { id: "heure-coup-fatigue", sectionId: "metabolisme-energie", type: "select", label: "A quelle heure survient ton coup de fatigue ?", options: [{ value: "matin", label: "Le matin (9h-11h)" }, { value: "midi", label: "Apres le dejeuner (13h-14h)" }, { value: "aprem", label: "Milieu d'aprem (15h-17h)" }, { value: "soir", label: "En fin de journee (18h+)" }, { value: "jamais", label: "Je n'ai pas de coup de fatigue" }] },
  { id: "thermogenese", sectionId: "metabolisme-energie", type: "select", label: "As-tu facilement froid ?", options: [{ value: "jamais", label: "Non, j'ai plutot chaud" }, { value: "parfois", label: "Parfois" }, { value: "souvent", label: "Souvent froid" }, { value: "toujours", label: "Toujours froid" }] },
  { id: "sudation", sectionId: "metabolisme-energie", type: "select", label: "Comment transpires-tu ?", options: [{ value: "peu", label: "Tres peu" }, { value: "normal", label: "Normalement" }, { value: "beaucoup", label: "Beaucoup" }, { value: "excessif", label: "Excessivement" }] },
  { id: "metabolisme-percu", sectionId: "metabolisme-energie", type: "select", label: "Comment qualifierais-tu ton metabolisme ?", options: [{ value: "lent", label: "Lent" }, { value: "normal", label: "Normal" }, { value: "rapide", label: "Rapide" }] },
  { id: "envies-sucre", sectionId: "metabolisme-energie", type: "select", label: "As-tu des envies de sucre ?", options: [{ value: "jamais", label: "Jamais" }, { value: "rarement", label: "Rarement" }, { value: "parfois", label: "Parfois" }, { value: "souvent", label: "Souvent" }, { value: "constamment", label: "Constamment" }] },
  { id: "faim-frequence", sectionId: "metabolisme-energie", type: "select", label: "A quelle frequence as-tu faim ?", options: [{ value: "rarement", label: "Rarement" }, { value: "3-repas", label: "3 repas par jour" }, { value: "souvent", label: "Souvent (5+ fois)" }, { value: "constamment", label: "Constamment" }] },

  // Section 4: Nutrition & Tracking (10 questions)
  { id: "nb-repas", sectionId: "nutrition-tracking", type: "select", label: "Combien de repas prends-tu par jour ?", options: [{ value: "1-2", label: "1-2 repas" }, { value: "3", label: "3 repas" }, { value: "4-5", label: "4-5 repas" }, { value: "6+", label: "6 repas ou plus" }] },
  { id: "petit-dejeuner", sectionId: "nutrition-tracking", type: "select", label: "Prends-tu un petit-dejeuner ?", options: [{ value: "toujours", label: "Toujours" }, { value: "souvent", label: "Souvent" }, { value: "parfois", label: "Parfois" }, { value: "jamais", label: "Jamais" }] },
  { id: "type-petit-dej", sectionId: "nutrition-tracking", type: "select", label: "Quel type de petit-dejeuner ?", options: [{ value: "sucre", label: "Sucre (cereales, pain, confiture)" }, { value: "sale", label: "Sale (oeufs, bacon, fromage)" }, { value: "mixte", label: "Mixte" }, { value: "liquide", label: "Liquide (smoothie, cafe)" }, { value: "rien", label: "Je ne mange pas le matin" }] },
  { id: "tracking-calories", sectionId: "nutrition-tracking", type: "select", label: "Fais-tu un tracking de tes calories ?", options: [{ value: "jamais", label: "Jamais" }, { value: "parfois", label: "Parfois" }, { value: "souvent", label: "Souvent" }, { value: "toujours", label: "Toujours" }] },
  { id: "calories-jour", sectionId: "nutrition-tracking", type: "select", label: "Estimation de tes calories quotidiennes ?", options: [{ value: "moins-1500", label: "Moins de 1500 kcal" }, { value: "1500-2000", label: "1500-2000 kcal" }, { value: "2000-2500", label: "2000-2500 kcal" }, { value: "2500-3000", label: "2500-3000 kcal" }, { value: "3000+", label: "Plus de 3000 kcal" }, { value: "inconnu", label: "Je ne sais pas" }] },
  { id: "proteines-jour", sectionId: "nutrition-tracking", type: "select", label: "Consommation de proteines par jour ?", options: [{ value: "faible", label: "Faible (moins de 50g)" }, { value: "moyenne", label: "Moyenne (50-100g)" }, { value: "bonne", label: "Bonne (100-150g)" }, { value: "haute", label: "Haute (150g+)" }, { value: "inconnu", label: "Je ne sais pas" }] },
  { id: "eau-jour", sectionId: "nutrition-tracking", type: "select", label: "Combien d'eau bois-tu par jour ?", options: [{ value: "moins-1L", label: "Moins de 1L" }, { value: "1-1.5L", label: "1-1.5L" }, { value: "1.5-2L", label: "1.5-2L" }, { value: "2-3L", label: "2-3L" }, { value: "3L+", label: "Plus de 3L" }] },
  { id: "regime-alimentaire", sectionId: "nutrition-tracking", type: "select", label: "Suis-tu un regime particulier ?", options: [{ value: "aucun", label: "Aucun" }, { value: "vegetarien", label: "Vegetarien" }, { value: "vegan", label: "Vegan" }, { value: "keto", label: "Cetogene" }, { value: "paleo", label: "Paleo" }, { value: "mediteraneen", label: "Mediterraneen" }, { value: "jeune-intermittent", label: "Jeune intermittent" }] },
  { id: "supplements", sectionId: "nutrition-tracking", type: "checkbox", label: "Quels supplements prends-tu ?", options: [{ value: "whey", label: "Whey/Proteine" }, { value: "creatine", label: "Creatine" }, { value: "vitamines", label: "Vitamines" }, { value: "omega3", label: "Omega-3" }, { value: "magnesium", label: "Magnesium" }, { value: "aucun", label: "Aucun" }] },
  { id: "repas-exterieur", sectionId: "nutrition-tracking", type: "select", label: "Combien de repas par semaine a l'exterieur ?", options: [{ value: "0", label: "Aucun" }, { value: "1-2", label: "1-2 repas" }, { value: "3-5", label: "3-5 repas" }, { value: "5+", label: "Plus de 5" }] },
  { id: "glucides-reveil", sectionId: "nutrition-tracking", type: "select", label: "Prends-tu des glucides des le reveil ?", options: [{ value: "oui-sucres", label: "Oui (cereales, pain, jus)" }, { value: "oui-complexes", label: "Oui (flocons d'avoine)" }, { value: "non-proteines", label: "Non (proteines/lipides d'abord)" }, { value: "jeune", label: "Non (jeune intermittent)" }] },
  { id: "diner-glucides", sectionId: "nutrition-tracking", type: "select", label: "Ton diner est-il riche en glucides ?", options: [{ value: "tres-riche", label: "Tres riche (pates, riz, pain)" }, { value: "modere", label: "Modere" }, { value: "faible", label: "Faible (proteines + legumes)" }, { value: "zero", label: "Quasi zero glucides" }] },
  { id: "huiles-cuisson", sectionId: "nutrition-tracking", type: "select", label: "Quelles huiles utilises-tu pour cuisiner ?", options: [{ value: "olive", label: "Olive (basse temp)" }, { value: "coco-ghee", label: "Coco/Ghee (stable haute temp)" }, { value: "tournesol", label: "Tournesol/Colza" }, { value: "friture", label: "Huiles de friture" }, { value: "beurre", label: "Beurre" }] },
  { id: "aliments-transformes", sectionId: "nutrition-tracking", type: "select", label: "Frequence des aliments ultra-transformes ?", options: [{ value: "jamais", label: "Jamais" }, { value: "rarement", label: "Rarement (1-2x/semaine)" }, { value: "parfois", label: "Parfois (3-5x/semaine)" }, { value: "souvent", label: "Souvent (quotidien)" }] },
  { id: "ble-gluten-freq", sectionId: "nutrition-tracking", type: "select", label: "Frequence de consommation de ble/gluten ?", options: [{ value: "jamais", label: "Jamais" }, { value: "rarement", label: "Rarement" }, { value: "modere", label: "Moderee (3-4x/semaine)" }, { value: "quotidien", label: "Quotidienne" }] },
  { id: "sucres-ajoutes", sectionId: "nutrition-tracking", type: "select", label: "Consommation de sucres ajoutes ?", options: [{ value: "zero", label: "Zero" }, { value: "faible", label: "Faible" }, { value: "moderee", label: "Moderee" }, { value: "elevee", label: "Elevee" }] },
  { id: "omega6-omega3", sectionId: "nutrition-tracking", type: "select", label: "Ratio Omega-6/Omega-3 estime ?", options: [{ value: "optimal", label: "Optimal (poisson gras, peu friture)" }, { value: "desequilibre", label: "Desequilibre (friture, peu de poisson)" }, { value: "inconnu", label: "Je ne sais pas" }] },

  // Section 5: Digestion & Microbiome (10 questions)
  { id: "digestion-qualite", sectionId: "digestion-microbiome", type: "select", label: "Comment qualifies-tu ta digestion ?", options: [{ value: "mauvaise", label: "Mauvaise" }, { value: "moyenne", label: "Moyenne" }, { value: "bonne", label: "Bonne" }, { value: "excellente", label: "Excellente" }] },
  { id: "ballonnements", sectionId: "digestion-microbiome", type: "select", label: "Souffres-tu de ballonnements ?", options: [{ value: "jamais", label: "Jamais" }, { value: "parfois", label: "Parfois" }, { value: "souvent", label: "Souvent" }, { value: "toujours", label: "Apres chaque repas" }] },
  { id: "transit", sectionId: "digestion-microbiome", type: "select", label: "Comment est ton transit ?", options: [{ value: "constipation", label: "Tendance constipation" }, { value: "normal", label: "Normal (1-2x/jour)" }, { value: "rapide", label: "Rapide (3+x/jour)" }, { value: "irregulier", label: "Irregulier" }] },
  { id: "reflux", sectionId: "digestion-microbiome", type: "select", label: "As-tu des reflux gastriques ?", options: [{ value: "jamais", label: "Jamais" }, { value: "rarement", label: "Rarement" }, { value: "parfois", label: "Parfois" }, { value: "souvent", label: "Souvent" }] },
  { id: "intolerance", sectionId: "digestion-microbiome", type: "checkbox", label: "As-tu des intolerances alimentaires ?", options: [{ value: "lactose", label: "Lactose" }, { value: "gluten", label: "Gluten" }, { value: "fodmap", label: "FODMAPs" }, { value: "histamine", label: "Histamine" }, { value: "aucune", label: "Aucune" }] },
  { id: "probiotiques", sectionId: "digestion-microbiome", type: "select", label: "Prends-tu des probiotiques ?", options: [{ value: "jamais", label: "Jamais" }, { value: "parfois", label: "Parfois" }, { value: "regulierement", label: "Regulierement" }] },
  { id: "aliments-fermentes", sectionId: "digestion-microbiome", type: "select", label: "Consommes-tu des aliments fermentes ?", options: [{ value: "jamais", label: "Jamais" }, { value: "parfois", label: "Parfois" }, { value: "souvent", label: "Souvent" }] },
  { id: "antibiotiques-recent", sectionId: "digestion-microbiome", type: "select", label: "As-tu pris des antibiotiques recemment ?", options: [{ value: "non", label: "Non" }, { value: "3-mois", label: "Il y a moins de 3 mois" }, { value: "6-mois", label: "Il y a 3-6 mois" }, { value: "1-an", label: "Il y a plus de 6 mois" }] },
  { id: "selles-aspect", sectionId: "digestion-microbiome", type: "select", label: "Aspect general de tes selles ?", options: [{ value: "1-2", label: "Dures, morcelees" }, { value: "3-4", label: "Normales, bien formees" }, { value: "5-6", label: "Molles" }, { value: "7", label: "Liquides" }] },
  { id: "douleurs-abdominales", sectionId: "digestion-microbiome", type: "select", label: "Frequence des douleurs abdominales ?", options: [{ value: "jamais", label: "Jamais" }, { value: "rarement", label: "Rarement" }, { value: "parfois", label: "Parfois" }, { value: "souvent", label: "Souvent" }] },

  // Section 6: Activite & Performance (10 questions)
  { id: "sport-frequence", sectionId: "activite-performance", type: "select", label: "Combien de fois par semaine fais-tu du sport ?", options: [{ value: "0", label: "Jamais" }, { value: "1-2", label: "1-2 fois" }, { value: "3-4", label: "3-4 fois" }, { value: "5+", label: "5 fois ou plus" }] },
  { id: "type-sport", sectionId: "activite-performance", type: "checkbox", label: "Quels types d'activites pratiques-tu ?", options: [{ value: "musculation", label: "Musculation" }, { value: "cardio", label: "Cardio" }, { value: "hiit", label: "HIIT" }, { value: "yoga", label: "Yoga/Pilates" }, { value: "sport-collectif", label: "Sports collectifs" }, { value: "natation", label: "Natation" }, { value: "course", label: "Course a pied" }, { value: "aucun", label: "Aucune activite" }] },
  { id: "duree-seance", sectionId: "activite-performance", type: "select", label: "Duree moyenne d'une seance ?", options: [{ value: "moins-30", label: "Moins de 30 min" }, { value: "30-45", label: "30-45 min" }, { value: "45-60", label: "45-60 min" }, { value: "60-90", label: "60-90 min" }, { value: "90+", label: "Plus de 90 min" }] },
  { id: "intensite-entrainement", sectionId: "activite-performance", type: "select", label: "Intensite moyenne de tes entrainements ?", options: [{ value: "leger", label: "Legere" }, { value: "modere", label: "Moderee" }, { value: "intense", label: "Intense" }, { value: "extreme", label: "Extreme" }] },
  { id: "recuperation", sectionId: "activite-performance", type: "select", label: "Qualite de ta recuperation ?", options: [{ value: "mauvaise", label: "Mauvaise" }, { value: "moyenne", label: "Moyenne" }, { value: "bonne", label: "Bonne" }, { value: "excellente", label: "Excellente" }] },
  { id: "courbatures", sectionId: "activite-performance", type: "select", label: "Frequence des courbatures ?", options: [{ value: "jamais", label: "Jamais" }, { value: "parfois", label: "Parfois" }, { value: "souvent", label: "Souvent" }, { value: "toujours", label: "Toujours" }] },
  { id: "performance-evolution", sectionId: "activite-performance", type: "select", label: "Comment evoluent tes performances ?", options: [{ value: "progression", label: "En progression" }, { value: "stagnation", label: "Stagnation" }, { value: "regression", label: "Regression" }] },
  { id: "blessures", sectionId: "activite-performance", type: "checkbox", label: "As-tu des blessures ou douleurs ?", options: [{ value: "epaule", label: "Epaule" }, { value: "genou", label: "Genou" }, { value: "dos", label: "Dos" }, { value: "hanche", label: "Hanche" }, { value: "cheville", label: "Cheville" }, { value: "aucune", label: "Aucune" }] },
  { id: "echauffement", sectionId: "activite-performance", type: "select", label: "Fais-tu un echauffement ?", options: [{ value: "jamais", label: "Jamais" }, { value: "parfois", label: "Parfois" }, { value: "toujours", label: "Toujours" }] },
  { id: "etirements", sectionId: "activite-performance", type: "select", label: "Fais-tu des etirements ?", options: [{ value: "jamais", label: "Jamais" }, { value: "parfois", label: "Parfois" }, { value: "toujours", label: "Toujours" }] },
  { id: "cardio-jeun", sectionId: "activite-performance", type: "select", label: "Fais-tu du cardio a jeun ?", options: [{ value: "jamais", label: "Jamais" }, { value: "parfois", label: "Parfois" }, { value: "souvent", label: "Souvent" }, { value: "toujours", label: "Toujours" }] },
  { id: "glucides-pre-cardio", sectionId: "activite-performance", type: "select", label: "Prends-tu des glucides avant le cardio ?", options: [{ value: "oui", label: "Oui" }, { value: "non", label: "Non (lipolyse maximale)" }, { value: "parfois", label: "Parfois" }, { value: "pas-cardio", label: "Je ne fais pas de cardio" }] },
  { id: "glucides-pre-muscu", sectionId: "activite-performance", type: "select", label: "Prends-tu des glucides avant la musculation ?", options: [{ value: "oui-repas", label: "Oui (repas complet)" }, { value: "oui-collation", label: "Oui (collation legere)" }, { value: "non", label: "Non (a jeun ou low-carb)" }, { value: "pas-muscu", label: "Je ne fais pas de musculation" }] },
  { id: "glucides-intra", sectionId: "activite-performance", type: "select", label: "Prends-tu des glucides pendant l'entrainement ?", options: [{ value: "oui-boisson", label: "Oui (boisson glucidique)" }, { value: "oui-solide", label: "Oui (banane, barre)" }, { value: "non", label: "Non" }] },
  { id: "bcaa-eaa-intra", sectionId: "activite-performance", type: "select", label: "Prends-tu des BCAA/EAA/HMB pendant l'entrainement ?", options: [{ value: "oui-bcaa", label: "Oui (BCAA)" }, { value: "oui-eaa", label: "Oui (EAA)" }, { value: "oui-hmb", label: "Oui (HMB)" }, { value: "non", label: "Non" }] },
  { id: "repas-post-training", sectionId: "activite-performance", type: "select", label: "Delai avant ton repas post-entrainement ?", options: [{ value: "immediat", label: "Immediat (< 30 min)" }, { value: "1h", label: "Dans l'heure" }, { value: "2h", label: "1-2 heures" }, { value: "plus", label: "Plus de 2 heures" }] },
  { id: "shake-post", sectionId: "activite-performance", type: "select", label: "Prends-tu un shake post-entrainement ?", options: [{ value: "whey-simple", label: "Whey seule" }, { value: "whey-glucides", label: "Whey + glucides rapides" }, { value: "gaineur", label: "Gaineur" }, { value: "non", label: "Non" }] },
  { id: "timing-training", sectionId: "activite-performance", type: "select", label: "A quel moment t'entraines-tu ?", options: [{ value: "matin-jeun", label: "Matin a jeun" }, { value: "matin-apres-pdj", label: "Matin apres petit-dej" }, { value: "midi", label: "Midi" }, { value: "aprem", label: "Apres-midi" }, { value: "soir", label: "Soir (apres 18h)" }] },

  // Section 7: Sommeil & Recuperation (10 questions)
  { id: "heures-sommeil", sectionId: "sommeil-recuperation", type: "select", label: "Combien d'heures dors-tu par nuit ?", options: [{ value: "moins-5", label: "Moins de 5h" }, { value: "5-6", label: "5-6h" }, { value: "6-7", label: "6-7h" }, { value: "7-8", label: "7-8h" }, { value: "8-9", label: "8-9h" }, { value: "9+", label: "Plus de 9h" }] },
  { id: "qualite-sommeil", sectionId: "sommeil-recuperation", type: "select", label: "Qualite de ton sommeil ?", options: [{ value: "mauvaise", label: "Mauvaise" }, { value: "moyenne", label: "Moyenne" }, { value: "bonne", label: "Bonne" }, { value: "excellente", label: "Excellente" }] },
  { id: "heure-coucher", sectionId: "sommeil-recuperation", type: "select", label: "A quelle heure te couches-tu ?", options: [{ value: "avant-22h", label: "Avant 22h" }, { value: "22h-23h", label: "22h-23h" }, { value: "23h-00h", label: "23h-minuit" }, { value: "00h-1h", label: "Minuit-1h" }, { value: "apres-1h", label: "Apres 1h" }] },
  { id: "heure-lever", sectionId: "sommeil-recuperation", type: "select", label: "A quelle heure te leves-tu ?", options: [{ value: "avant-6h", label: "Avant 6h" }, { value: "6h-7h", label: "6h-7h" }, { value: "7h-8h", label: "7h-8h" }, { value: "8h-9h", label: "8h-9h" }, { value: "apres-9h", label: "Apres 9h" }] },
  { id: "endormissement", sectionId: "sommeil-recuperation", type: "select", label: "Temps pour t'endormir ?", options: [{ value: "rapide", label: "Moins de 15 min" }, { value: "normal", label: "15-30 min" }, { value: "long", label: "30-60 min" }, { value: "tres-long", label: "Plus d'1 heure" }] },
  { id: "reveils-nocturnes", sectionId: "sommeil-recuperation", type: "select", label: "Te reveilles-tu la nuit ?", options: [{ value: "jamais", label: "Jamais" }, { value: "parfois", label: "Parfois (1-2x)" }, { value: "souvent", label: "Souvent (3+x)" }] },
  { id: "reveil-repose", sectionId: "sommeil-recuperation", type: "select", label: "Te sens-tu repose au reveil ?", options: [{ value: "jamais", label: "Jamais" }, { value: "rarement", label: "Rarement" }, { value: "parfois", label: "Parfois" }, { value: "souvent", label: "Souvent" }, { value: "toujours", label: "Toujours" }] },
  { id: "sieste", sectionId: "sommeil-recuperation", type: "select", label: "Fais-tu la sieste ?", options: [{ value: "jamais", label: "Jamais" }, { value: "parfois", label: "Parfois" }, { value: "quotidien", label: "Quotidiennement" }] },
  { id: "ecrans-soir", sectionId: "sommeil-recuperation", type: "select", label: "Utilises-tu des ecrans avant de dormir ?", options: [{ value: "jamais", label: "Jamais" }, { value: "parfois", label: "Parfois" }, { value: "souvent", label: "Souvent" }, { value: "toujours", label: "Toujours" }] },
  { id: "chambre-temperature", sectionId: "sommeil-recuperation", type: "select", label: "Temperature de ta chambre ?", options: [{ value: "froid", label: "Froide (<18C)" }, { value: "optimal", label: "Optimale (18-20C)" }, { value: "chaud", label: "Chaude (>20C)" }] },

  // Section 8: HRV & Cardiaque (8 questions)
  { id: "hrv-mesure", sectionId: "hrv-cardiaque", type: "select", label: "Mesures-tu ta HRV (variabilite cardiaque) ?", options: [{ value: "non", label: "Non" }, { value: "parfois", label: "Parfois" }, { value: "regulierement", label: "Regulierement" }] },
  { id: "hrv-valeur", sectionId: "hrv-cardiaque", type: "select", label: "Si oui, quelle est ta HRV moyenne ?", options: [{ value: "moins-30", label: "Moins de 30 ms" }, { value: "30-50", label: "30-50 ms" }, { value: "50-70", label: "50-70 ms" }, { value: "70+", label: "Plus de 70 ms" }, { value: "inconnu", label: "Je ne mesure pas" }] },
  { id: "fc-repos", sectionId: "hrv-cardiaque", type: "select", label: "Frequence cardiaque au repos ?", options: [{ value: "moins-50", label: "Moins de 50 bpm" }, { value: "50-60", label: "50-60 bpm" }, { value: "60-70", label: "60-70 bpm" }, { value: "70-80", label: "70-80 bpm" }, { value: "80+", label: "Plus de 80 bpm" }, { value: "inconnu", label: "Je ne sais pas" }] },
  { id: "tension-arterielle", sectionId: "hrv-cardiaque", type: "select", label: "Connais-tu ta tension arterielle ?", options: [{ value: "basse", label: "Basse (<100/60)" }, { value: "normale", label: "Normale (120/80)" }, { value: "elevee", label: "Elevee (>130/85)" }, { value: "haute", label: "Haute (>140/90)" }, { value: "inconnu", label: "Je ne sais pas" }] },
  { id: "montre-connectee", sectionId: "hrv-cardiaque", type: "select", label: "Utilises-tu une montre connectee ?", options: [{ value: "non", label: "Non" }, { value: "oui", label: "Oui" }] },
  { id: "type-montre", sectionId: "hrv-cardiaque", type: "select", label: "Si oui, laquelle ?", options: [{ value: "apple", label: "Apple Watch" }, { value: "garmin", label: "Garmin" }, { value: "whoop", label: "Whoop" }, { value: "fitbit", label: "Fitbit" }, { value: "samsung", label: "Samsung" }, { value: "oura", label: "Oura Ring" }, { value: "autre", label: "Autre" }, { value: "aucune", label: "Je n'en utilise pas" }] },
  { id: "palpitations", sectionId: "hrv-cardiaque", type: "select", label: "Ressens-tu des palpitations ?", options: [{ value: "jamais", label: "Jamais" }, { value: "rarement", label: "Rarement" }, { value: "parfois", label: "Parfois" }, { value: "souvent", label: "Souvent" }] },
  { id: "essoufflement", sectionId: "hrv-cardiaque", type: "select", label: "T'essouffles-tu facilement ?", options: [{ value: "jamais", label: "Jamais" }, { value: "effort-intense", label: "Seulement a l'effort intense" }, { value: "effort-modere", label: "A l'effort modere" }, { value: "facilement", label: "Facilement" }] },

  // Section 9: Cardio & Endurance (10 questions)
  { id: "cardio-frequence", sectionId: "cardio-endurance", type: "select", label: "Combien de seances de cardio fais-tu par semaine ?", options: [{ value: "0", label: "Aucune" }, { value: "1-2", label: "1-2 seances" }, { value: "3-4", label: "3-4 seances" }, { value: "5+", label: "5 ou plus" }] },
  { id: "cardio-type", sectionId: "cardio-endurance", type: "checkbox", label: "Quels types de cardio pratiques-tu ?", options: [{ value: "marche", label: "Marche rapide" }, { value: "course", label: "Course a pied" }, { value: "velo", label: "Velo (exterieur ou indoor)" }, { value: "natation", label: "Natation" }, { value: "rameur", label: "Rameur" }, { value: "elliptique", label: "Elliptique" }, { value: "hiit", label: "HIIT" }, { value: "aucun", label: "Aucun cardio" }] },
  { id: "cardio-duree", sectionId: "cardio-endurance", type: "select", label: "Duree moyenne d'une seance cardio ?", options: [{ value: "moins-20", label: "Moins de 20 min" }, { value: "20-30", label: "20-30 min" }, { value: "30-45", label: "30-45 min" }, { value: "45-60", label: "45-60 min" }, { value: "60+", label: "Plus de 60 min" }, { value: "pas-cardio", label: "Je ne fais pas de cardio" }] },
  { id: "zone2-connaissance", sectionId: "cardio-endurance", type: "select", label: "Connais-tu l'entrainement en Zone 2 (cardio basse intensite) ?", options: [{ value: "non", label: "Non, jamais entendu parler" }, { value: "vaguement", label: "Vaguement" }, { value: "oui-pratique-pas", label: "Oui mais je ne pratique pas" }, { value: "oui-pratique", label: "Oui et je le pratique" }] },
  { id: "zone2-frequence", sectionId: "cardio-endurance", type: "select", label: "Combien de temps passes-tu en Zone 2 par semaine ?", options: [{ value: "0", label: "0 min" }, { value: "moins-60", label: "Moins de 60 min" }, { value: "60-120", label: "60-120 min" }, { value: "120-180", label: "120-180 min" }, { value: "180+", label: "Plus de 180 min" }] },
  { id: "vo2max-estime", sectionId: "cardio-endurance", type: "select", label: "Connais-tu ta VO2max estimee ?", options: [{ value: "moins-30", label: "Moins de 30 ml/kg/min (faible)" }, { value: "30-40", label: "30-40 ml/kg/min (moyen)" }, { value: "40-50", label: "40-50 ml/kg/min (bon)" }, { value: "50+", label: "Plus de 50 ml/kg/min (excellent)" }, { value: "inconnu", label: "Je ne sais pas" }] },
  { id: "lactate-threshold", sectionId: "cardio-endurance", type: "select", label: "Connais-tu ton seuil lactique ?", options: [{ value: "non", label: "Non" }, { value: "oui-test", label: "Oui (test en labo)" }, { value: "oui-estime", label: "Oui (estime par montre)" }, { value: "inconnu", label: "Je ne sais pas ce que c'est" }] },
  { id: "hiit-ratio", sectionId: "cardio-endurance", type: "select", label: "Quel ratio HIIT vs cardio basse intensite dans ta semaine ?", options: [{ value: "100-hiit", label: "100% HIIT" }, { value: "80-hiit", label: "80% HIIT / 20% basse intensite" }, { value: "50-50", label: "50% HIIT / 50% basse intensite" }, { value: "20-hiit", label: "20% HIIT / 80% basse intensite" }, { value: "100-liss", label: "100% basse intensite (LISS/Zone 2)" }, { value: "pas-cardio", label: "Je ne fais pas de cardio" }] },
  { id: "fc-cardio", sectionId: "cardio-endurance", type: "select", label: "A quelle FC t'entraines-tu en cardio generalement ?", options: [{ value: "moins-120", label: "Moins de 120 bpm (tres leger)" }, { value: "120-140", label: "120-140 bpm (Zone 2)" }, { value: "140-160", label: "140-160 bpm (Zone 3)" }, { value: "160-180", label: "160-180 bpm (Zone 4)" }, { value: "180+", label: "Plus de 180 bpm (max)" }, { value: "pas-mesure", label: "Je ne mesure pas" }] },
  { id: "endurance-objectif", sectionId: "cardio-endurance", type: "select", label: "Quel est ton objectif principal en cardio ?", options: [{ value: "perte-gras", label: "Perte de gras" }, { value: "endurance", label: "Ameliorer l'endurance" }, { value: "sante-cardiaque", label: "Sante cardiovasculaire" }, { value: "performance", label: "Performance sportive" }, { value: "aucun", label: "Aucun objectif specifique" }] },

  // Section 10: Analyses & Biomarqueurs (10 questions)
  { id: "bilan-sanguin-recent", sectionId: "analyses-biomarqueurs", type: "select", label: "As-tu fait un bilan sanguin recemment ?", options: [{ value: "non", label: "Non" }, { value: "3-mois", label: "Il y a moins de 3 mois" }, { value: "6-mois", label: "Il y a 3-6 mois" }, { value: "1-an", label: "Il y a plus de 6 mois" }] },
  { id: "glycemie-statut", sectionId: "analyses-biomarqueurs", type: "select", label: "Ta glycemie a jeun est-elle normale ?", options: [{ value: "normale", label: "Normale" }, { value: "elevee", label: "Elevee" }, { value: "basse", label: "Basse" }, { value: "inconnu", label: "Je ne sais pas" }] },
  { id: "cholesterol-statut", sectionId: "analyses-biomarqueurs", type: "select", label: "Ton cholesterol est-il normal ?", options: [{ value: "normal", label: "Normal" }, { value: "eleve", label: "Eleve" }, { value: "inconnu", label: "Je ne sais pas" }] },
  { id: "vitamine-d-statut", sectionId: "analyses-biomarqueurs", type: "select", label: "Ton taux de vitamine D ?", options: [{ value: "deficient", label: "Deficient" }, { value: "insuffisant", label: "Insuffisant" }, { value: "optimal", label: "Optimal" }, { value: "inconnu", label: "Je ne sais pas" }] },
  { id: "fer-statut", sectionId: "analyses-biomarqueurs", type: "select", label: "Ton taux de fer/ferritine ?", options: [{ value: "bas", label: "Bas" }, { value: "normal", label: "Normal" }, { value: "eleve", label: "Eleve" }, { value: "inconnu", label: "Je ne sais pas" }] },
  { id: "thyroide-statut", sectionId: "analyses-biomarqueurs", type: "select", label: "Ta thyroide (TSH) est-elle normale ?", options: [{ value: "normale", label: "Normale" }, { value: "hypo", label: "Hypothyroidie" }, { value: "hyper", label: "Hyperthyroidie" }, { value: "inconnu", label: "Je ne sais pas" }] },
  { id: "testosterone-statut", sectionId: "analyses-biomarqueurs", type: "select", label: "Ton taux de testosterone ?", options: [{ value: "bas", label: "Bas" }, { value: "normal", label: "Normal" }, { value: "eleve", label: "Eleve" }, { value: "inconnu", label: "Je ne sais pas" }], showFor: "homme" },
  { id: "estrogenes-statut", sectionId: "analyses-biomarqueurs", type: "select", label: "Ton taux d'estrogenes ?", options: [{ value: "bas", label: "Bas" }, { value: "normal", label: "Normal" }, { value: "eleve", label: "Eleve" }, { value: "inconnu", label: "Je ne sais pas" }], showFor: "femme" },
  { id: "inflammation-statut", sectionId: "analyses-biomarqueurs", type: "select", label: "As-tu des marqueurs d'inflammation eleves ?", options: [{ value: "non", label: "Non" }, { value: "oui", label: "Oui (CRP elevee)" }, { value: "inconnu", label: "Je ne sais pas" }] },
  { id: "foie-statut", sectionId: "analyses-biomarqueurs", type: "select", label: "Tes marqueurs hepatiques sont-ils normaux ?", options: [{ value: "normaux", label: "Normaux" }, { value: "eleves", label: "Eleves" }, { value: "inconnu", label: "Je ne sais pas" }] },
  { id: "reins-statut", sectionId: "analyses-biomarqueurs", type: "select", label: "Tes marqueurs renaux sont-ils normaux ?", options: [{ value: "normaux", label: "Normaux" }, { value: "anormaux", label: "Anormaux" }, { value: "inconnu", label: "Je ne sais pas" }] },

  // Section 10: Hormones & Stress (10 questions)
  { id: "niveau-stress", sectionId: "hormones-stress", type: "select", label: "Quel est ton niveau de stress quotidien ?", options: [{ value: "aucun", label: "Aucun stress" }, { value: "leger", label: "Leger" }, { value: "modere", label: "Modere" }, { value: "eleve", label: "Eleve" }, { value: "extreme", label: "Extreme" }] },
  { id: "sources-stress", sectionId: "hormones-stress", type: "checkbox", label: "Quelles sont tes sources de stress ?", options: [{ value: "travail", label: "Travail" }, { value: "finances", label: "Finances" }, { value: "relations", label: "Relations" }, { value: "sante", label: "Sante" }, { value: "famille", label: "Famille" }, { value: "aucune", label: "Aucune" }] },
  { id: "gestion-stress", sectionId: "hormones-stress", type: "checkbox", label: "Comment geres-tu ton stress ?", options: [{ value: "meditation", label: "Meditation" }, { value: "sport", label: "Sport" }, { value: "respiration", label: "Respiration" }, { value: "nature", label: "Nature" }, { value: "musique", label: "Musique" }, { value: "rien", label: "Rien de special" }] },
  { id: "anxiete", sectionId: "hormones-stress", type: "select", label: "Niveau d'anxiete general ?", options: [{ value: "aucune", label: "Aucune" }, { value: "legere", label: "Legere" }, { value: "moderee", label: "Moderee" }, { value: "forte", label: "Forte" }] },
  { id: "humeur-fluctuation", sectionId: "hormones-stress", type: "select", label: "Tes humeurs fluctuent-elles ?", options: [{ value: "stable", label: "Tres stable" }, { value: "parfois", label: "Parfois" }, { value: "souvent", label: "Souvent" }, { value: "constamment", label: "Constamment" }] },
  { id: "libido", sectionId: "hormones-stress", type: "select", label: "Comment qualifies-tu ta libido ?", options: [{ value: "basse", label: "Basse" }, { value: "moyenne", label: "Moyenne" }, { value: "bonne", label: "Bonne" }, { value: "haute", label: "Haute" }] },
  { id: "cortisol-symptomes", sectionId: "hormones-stress", type: "checkbox", label: "Ressens-tu ces symptomes de cortisol eleve ?", options: [{ value: "fatigue-matin", label: "Fatigue le matin" }, { value: "energie-soir", label: "Regain d'energie le soir" }, { value: "graisse-abdominale", label: "Graisse abdominale" }, { value: "irritabilite", label: "Irritabilite" }, { value: "aucun", label: "Aucun" }] },
  { id: "thyroide-symptomes", sectionId: "hormones-stress", type: "checkbox", label: "Symptomes thyroidiens ?", options: [{ value: "frilosite", label: "Frilosite" }, { value: "fatigue", label: "Fatigue" }, { value: "prise-poids", label: "Prise de poids" }, { value: "perte-cheveux", label: "Perte de cheveux" }, { value: "aucun", label: "Aucun" }] },
  { id: "cycle-menstruel", sectionId: "hormones-stress", type: "select", label: "Regularite de ton cycle menstruel ?", options: [{ value: "regulier", label: "Regulier (28-32 jours)" }, { value: "irregulier", label: "Irregulier" }, { value: "absent", label: "Absent / Menopause" }], showFor: "femme" },
  { id: "syndrome-premenstruel", sectionId: "hormones-stress", type: "select", label: "Souffres-tu de syndrome premenstruel ?", options: [{ value: "non", label: "Non" }, { value: "leger", label: "Leger" }, { value: "modere", label: "Modere" }, { value: "severe", label: "Severe" }], showFor: "femme" },
  { id: "contraception", sectionId: "hormones-stress", type: "select", label: "Utilises-tu une contraception hormonale ?", options: [{ value: "non", label: "Non" }, { value: "pilule", label: "Pilule" }, { value: "sterilet-hormonal", label: "Sterilet hormonal" }, { value: "implant", label: "Implant" }, { value: "autre", label: "Autre" }], showFor: "femme" },
  { id: "erection-qualite", sectionId: "hormones-stress", type: "select", label: "Qualite de tes erections matinales ?", options: [{ value: "absentes", label: "Absentes" }, { value: "rares", label: "Rares" }, { value: "regulieres", label: "Regulieres" }, { value: "quotidiennes", label: "Quotidiennes et fortes" }], showFor: "homme" },
  { id: "endometriose", sectionId: "hormones-stress", type: "select", label: "Souffres-tu d'endometriose ?", options: [{ value: "non", label: "Non" }, { value: "suspectee", label: "Suspectee" }, { value: "diagnostiquee", label: "Diagnostiquee" }], showFor: "femme" },
  { id: "sopk", sectionId: "hormones-stress", type: "select", label: "As-tu un syndrome des ovaires polykystiques (SOPK) ?", options: [{ value: "non", label: "Non" }, { value: "suspectee", label: "Suspecte" }, { value: "diagnostique", label: "Diagnostique" }], showFor: "femme" },
  { id: "menopause", sectionId: "hormones-stress", type: "select", label: "Es-tu en perimenopause ou menopause ?", options: [{ value: "non", label: "Non" }, { value: "perimenopause", label: "Perimenopause" }, { value: "menopause", label: "Menopause" }], showFor: "femme" },
  { id: "sii-femme", sectionId: "hormones-stress", type: "select", label: "Souffres-tu du syndrome de l'intestin irritable (SII) ?", options: [{ value: "non", label: "Non" }, { value: "leger", label: "Leger" }, { value: "modere", label: "Modere" }, { value: "severe", label: "Severe" }], showFor: "femme" },
  { id: "prostate", sectionId: "hormones-stress", type: "select", label: "As-tu des symptomes prostatiques (envies frequentes, difficulte a uriner) ?", options: [{ value: "non", label: "Non" }, { value: "legers", label: "Legers" }, { value: "moderes", label: "Moderes" }, { value: "importants", label: "Importants" }], showFor: "homme" },
  { id: "calvitie", sectionId: "hormones-stress", type: "select", label: "Observes-tu une perte de cheveux ou calvitie ?", options: [{ value: "non", label: "Non" }, { value: "legere", label: "Legere" }, { value: "moderee", label: "Moderee" }, { value: "avancee", label: "Avancee" }], showFor: "homme" },
  { id: "motivation", sectionId: "hormones-stress", type: "select", label: "Niveau de motivation general ?", options: [{ value: "tres-bas", label: "Tres bas" }, { value: "bas", label: "Bas" }, { value: "moyen", label: "Moyen" }, { value: "bon", label: "Bon" }, { value: "excellent", label: "Excellent" }] },

  // Section 11: Lifestyle & Substances (10 questions)
  { id: "cafe-jour", sectionId: "lifestyle-substances", type: "select", label: "Combien de cafes par jour ?", options: [{ value: "0", label: "Aucun" }, { value: "1-2", label: "1-2" }, { value: "3-4", label: "3-4" }, { value: "5+", label: "5 ou plus" }] },
  { id: "dernier-cafe", sectionId: "lifestyle-substances", type: "select", label: "Heure du dernier cafe ?", options: [{ value: "avant-12h", label: "Avant midi" }, { value: "12h-14h", label: "12h-14h" }, { value: "14h-16h", label: "14h-16h" }, { value: "apres-16h", label: "Apres 16h" }, { value: "pas-cafe", label: "Je ne bois pas de cafe" }] },
  { id: "alcool-semaine", sectionId: "lifestyle-substances", type: "select", label: "Verres d'alcool par semaine ?", options: [{ value: "0", label: "Aucun" }, { value: "1-3", label: "1-3 verres" }, { value: "4-7", label: "4-7 verres" }, { value: "8-14", label: "8-14 verres" }, { value: "15+", label: "Plus de 15" }] },
  { id: "tabac", sectionId: "lifestyle-substances", type: "select", label: "Fumes-tu ?", options: [{ value: "non", label: "Non" }, { value: "ex-fumeur", label: "Ex-fumeur" }, { value: "occasionnel", label: "Occasionnellement" }, { value: "quotidien", label: "Quotidiennement" }] },
  { id: "cannabis", sectionId: "lifestyle-substances", type: "select", label: "Consommes-tu du cannabis ?", options: [{ value: "non", label: "Non" }, { value: "occasionnel", label: "Occasionnellement" }, { value: "regulier", label: "Regulierement" }] },
  { id: "temps-ecran", sectionId: "lifestyle-substances", type: "select", label: "Temps d'ecran quotidien (hors travail) ?", options: [{ value: "moins-1h", label: "Moins d'1h" }, { value: "1-2h", label: "1-2h" }, { value: "2-4h", label: "2-4h" }, { value: "4-6h", label: "4-6h" }, { value: "6h+", label: "Plus de 6h" }] },
  { id: "exposition-soleil", sectionId: "lifestyle-substances", type: "select", label: "Exposition au soleil ?", options: [{ value: "rare", label: "Rarement" }, { value: "parfois", label: "Parfois" }, { value: "regulier", label: "Regulierement" }] },
  { id: "nature-frequence", sectionId: "lifestyle-substances", type: "select", label: "Temps passe dans la nature ?", options: [{ value: "jamais", label: "Jamais" }, { value: "rare", label: "Rarement" }, { value: "hebdo", label: "Chaque semaine" }, { value: "quotidien", label: "Quotidiennement" }] },
  { id: "meditation-pratique", sectionId: "lifestyle-substances", type: "select", label: "Pratiques-tu la meditation ?", options: [{ value: "jamais", label: "Jamais" }, { value: "parfois", label: "Parfois" }, { value: "regulier", label: "Regulierement" }] },
  { id: "douche-froide", sectionId: "lifestyle-substances", type: "select", label: "Prends-tu des douches froides ?", options: [{ value: "jamais", label: "Jamais" }, { value: "parfois", label: "Parfois" }, { value: "regulier", label: "Regulierement" }] },

  // Section 12: Biomecanique & Mobilite (10 questions)
  { id: "douleurs-chroniques", sectionId: "biomecanique-mobilite", type: "checkbox", label: "As-tu des douleurs chroniques ?", options: [{ value: "dos", label: "Dos" }, { value: "nuque", label: "Nuque" }, { value: "epaules", label: "Epaules" }, { value: "genoux", label: "Genoux" }, { value: "hanches", label: "Hanches" }, { value: "aucune", label: "Aucune" }] },
  { id: "posture-travail", sectionId: "biomecanique-mobilite", type: "select", label: "Posture au travail ?", options: [{ value: "assis", label: "Assis (bureau)" }, { value: "debout", label: "Debout" }, { value: "mixte", label: "Mixte" }, { value: "physique", label: "Travail physique" }] },
  { id: "heures-assis", sectionId: "biomecanique-mobilite", type: "select", label: "Heures assis par jour ?", options: [{ value: "moins-4h", label: "Moins de 4h" }, { value: "4-6h", label: "4-6h" }, { value: "6-8h", label: "6-8h" }, { value: "8-10h", label: "8-10h" }, { value: "10h+", label: "Plus de 10h" }] },
  { id: "mobilite-generale", sectionId: "biomecanique-mobilite", type: "select", label: "Comment qualifies-tu ta mobilite ?", options: [{ value: "raide", label: "Tres raide" }, { value: "moyenne", label: "Moyenne" }, { value: "bonne", label: "Bonne" }, { value: "excellente", label: "Excellente" }] },
  { id: "squat-profond", sectionId: "biomecanique-mobilite", type: "select", label: "Peux-tu faire un squat complet (talons au sol) ?", options: [{ value: "oui", label: "Oui, facilement" }, { value: "difficulte", label: "Avec difficulte" }, { value: "non", label: "Non" }] },
  { id: "toucher-orteils", sectionId: "biomecanique-mobilite", type: "select", label: "Peux-tu toucher tes orteils jambes tendues ?", options: [{ value: "oui", label: "Oui" }, { value: "presque", label: "Presque" }, { value: "non", label: "Non" }] },
  { id: "asymetrie", sectionId: "biomecanique-mobilite", type: "select", label: "Ressens-tu des asymetries gauche/droite ?", options: [{ value: "non", label: "Non" }, { value: "legeres", label: "Legeres" }, { value: "importantes", label: "Importantes" }] },
  { id: "travail-mobilite", sectionId: "biomecanique-mobilite", type: "select", label: "Travailles-tu ta mobilite ?", options: [{ value: "jamais", label: "Jamais" }, { value: "parfois", label: "Parfois" }, { value: "regulierement", label: "Regulierement" }] },
  { id: "foam-roller", sectionId: "biomecanique-mobilite", type: "select", label: "Utilises-tu un foam roller ou massage gun ?", options: [{ value: "jamais", label: "Jamais" }, { value: "parfois", label: "Parfois" }, { value: "regulierement", label: "Regulierement" }] },
  { id: "kine-osteo", sectionId: "biomecanique-mobilite", type: "select", label: "Consultes-tu un kine ou osteo ?", options: [{ value: "jamais", label: "Jamais" }, { value: "rarement", label: "Rarement" }, { value: "regulierement", label: "Regulierement" }] },

  // Section 13: Psychologie & Mental (14 questions)
  { id: "tca-historique", sectionId: "psychologie-mental", type: "select", label: "As-tu deja souffert de troubles alimentaires (TCA) ?", options: [{ value: "jamais", label: "Jamais" }, { value: "passe", label: "Dans le passe" }, { value: "actuel", label: "Actuellement" }, { value: "incertain", label: "Pas sur(e)" }] },
  { id: "tca-type", sectionId: "psychologie-mental", type: "checkbox", label: "Si oui, quel(s) type(s) de comportement ?", options: [{ value: "restriction", label: "Restriction calorique extreme" }, { value: "binge", label: "Crises d'hyperphagie (binge eating)" }, { value: "purge", label: "Comportements purgatifs" }, { value: "orthorexie", label: "Obsession de manger sain (orthorexie)" }, { value: "comptage", label: "Comptage obsessionnel des calories" }, { value: "aucun", label: "Aucun / Non concerne" }] },
  { id: "relation-nourriture", sectionId: "psychologie-mental", type: "select", label: "Comment decrirais-tu ta relation avec la nourriture ?", options: [{ value: "saine", label: "Saine et equilibree" }, { value: "complexe", label: "Complexe mais geree" }, { value: "difficile", label: "Difficile au quotidien" }, { value: "toxique", label: "Tres problematique" }] },
  { id: "depression-vecu", sectionId: "psychologie-mental", type: "select", label: "As-tu vecu ou vis-tu des episodes depressifs ?", options: [{ value: "jamais", label: "Jamais" }, { value: "passe", label: "Dans le passe" }, { value: "leger-actuel", label: "Actuellement (leger)" }, { value: "modere-actuel", label: "Actuellement (modere a severe)" }] },
  { id: "depression-symptomes", sectionId: "psychologie-mental", type: "checkbox", label: "Quels symptomes ressens-tu regulierement ?", options: [{ value: "tristesse", label: "Tristesse persistante" }, { value: "anhedonie", label: "Perte de plaisir / interet" }, { value: "isolement", label: "Besoin d'isolement" }, { value: "fatigue-mentale", label: "Fatigue mentale intense" }, { value: "ideation", label: "Pensees negatives recurrentes" }, { value: "aucun", label: "Aucun de ces symptomes" }] },
  { id: "trauma-vecu", sectionId: "psychologie-mental", type: "select", label: "As-tu vecu des evenements traumatiques ?", options: [{ value: "non", label: "Non" }, { value: "oui-traite", label: "Oui, mais j'ai fait un travail dessus" }, { value: "oui-non-traite", label: "Oui, non encore traite" }, { value: "prefere-pas-dire", label: "Je prefere ne pas repondre" }] },
  { id: "trauma-impact", sectionId: "psychologie-mental", type: "select", label: "Ces evenements impactent-ils encore ta vie quotidienne ?", options: [{ value: "na", label: "Non concerne" }, { value: "non", label: "Non, plus maintenant" }, { value: "parfois", label: "Parfois" }, { value: "souvent", label: "Souvent" }, { value: "constamment", label: "Constamment" }] },
  { id: "estime-soi", sectionId: "psychologie-mental", type: "select", label: "Comment evalues-tu ton estime de toi ?", options: [{ value: "tres-basse", label: "Tres basse" }, { value: "basse", label: "Basse" }, { value: "moyenne", label: "Moyenne" }, { value: "bonne", label: "Bonne" }, { value: "excellente", label: "Excellente" }] },
  { id: "motivation-profonde", sectionId: "psychologie-mental", type: "select", label: "Qu'est-ce qui te motive vraiment dans cette demarche ?", options: [{ value: "sante", label: "Ma sante a long terme" }, { value: "apparence", label: "Mon apparence physique" }, { value: "performance", label: "Mes performances" }, { value: "mental", label: "Mon bien-etre mental" }, { value: "prouver", label: "Me prouver quelque chose" }, { value: "autres", label: "Pour les autres (famille, partenaire)" }] },
  { id: "modele-inspiration", sectionId: "psychologie-mental", type: "select", label: "As-tu un modele ou une inspiration ?", options: [{ value: "non", label: "Non, je me concentre sur moi" }, { value: "celebrite", label: "Une personnalite publique" }, { value: "proche", label: "Une personne de mon entourage" }, { value: "ancien-moi", label: "Une ancienne version de moi" }, { value: "ideal", label: "Un ideal que je me suis cree" }] },
  { id: "blocages-perso", sectionId: "psychologie-mental", type: "checkbox", label: "Quels blocages personnels t'empechent d'avancer ?", options: [{ value: "manque-temps", label: "Manque de temps" }, { value: "manque-motivation", label: "Manque de motivation" }, { value: "peur-echec", label: "Peur de l'echec" }, { value: "perfectionnisme", label: "Perfectionnisme" }, { value: "auto-sabotage", label: "Auto-sabotage" }, { value: "environnement", label: "Environnement non favorable" }, { value: "aucun", label: "Aucun blocage particulier" }] },
  { id: "soutien-social", sectionId: "psychologie-mental", type: "select", label: "Te sens-tu soutenu(e) dans tes objectifs ?", options: [{ value: "pas-du-tout", label: "Pas du tout" }, { value: "peu", label: "Peu" }, { value: "moyennement", label: "Moyennement" }, { value: "bien", label: "Bien entoure(e)" }, { value: "tres-bien", label: "Tres bien entoure(e)" }] },
  { id: "suivi-psy", sectionId: "psychologie-mental", type: "select", label: "Es-tu suivi(e) par un professionnel de sante mentale ?", options: [{ value: "non", label: "Non" }, { value: "passe", label: "Dans le passe" }, { value: "actuel", label: "Actuellement" }] },
  { id: "objectif-transformation", sectionId: "psychologie-mental", type: "textarea", label: "En une phrase, quel est ton objectif de transformation profond ?", placeholder: "Ex: Me sentir enfin bien dans mon corps et retrouver confiance en moi..." },

  // Section 14: Neurotransmetteurs & Cognition (8 questions)
  { id: "concentration", sectionId: "neurotransmetteurs", type: "select", label: "Comment est ta concentration ?", options: [{ value: "mauvaise", label: "Mauvaise" }, { value: "moyenne", label: "Moyenne" }, { value: "bonne", label: "Bonne" }, { value: "excellente", label: "Excellente" }] },
  { id: "memoire", sectionId: "neurotransmetteurs", type: "select", label: "Comment est ta memoire ?", options: [{ value: "mauvaise", label: "Mauvaise" }, { value: "moyenne", label: "Moyenne" }, { value: "bonne", label: "Bonne" }, { value: "excellente", label: "Excellente" }] },
  { id: "brain-fog", sectionId: "neurotransmetteurs", type: "select", label: "As-tu du brouillard mental (brain fog) ?", options: [{ value: "jamais", label: "Jamais" }, { value: "parfois", label: "Parfois" }, { value: "souvent", label: "Souvent" }, { value: "constamment", label: "Constamment" }] },
  { id: "humeur-generale", sectionId: "neurotransmetteurs", type: "select", label: "Comment est ton humeur generale ?", options: [{ value: "deprime", label: "Deprime" }, { value: "neutre", label: "Neutre" }, { value: "positive", label: "Positive" }, { value: "excellente", label: "Excellente" }] },
  { id: "procrastination", sectionId: "neurotransmetteurs", type: "select", label: "As-tu tendance a procrastiner ?", options: [{ value: "jamais", label: "Jamais" }, { value: "parfois", label: "Parfois" }, { value: "souvent", label: "Souvent" }, { value: "toujours", label: "Toujours" }] },
  { id: "impulsivite", sectionId: "neurotransmetteurs", type: "select", label: "Niveau d'impulsivite ?", options: [{ value: "tres-reflechi", label: "Tres reflechi" }, { value: "reflechi", label: "Reflechi" }, { value: "impulsif", label: "Impulsif" }, { value: "tres-impulsif", label: "Tres impulsif" }] },
  { id: "creativite", sectionId: "neurotransmetteurs", type: "select", label: "Comment est ta creativite ?", options: [{ value: "basse", label: "Basse" }, { value: "moyenne", label: "Moyenne" }, { value: "bonne", label: "Bonne" }, { value: "excellente", label: "Excellente" }] },
  { id: "apprentissage", sectionId: "neurotransmetteurs", type: "select", label: "Facilite a apprendre de nouvelles choses ?", options: [{ value: "difficile", label: "Difficile" }, { value: "moyen", label: "Moyen" }, { value: "facile", label: "Facile" }, { value: "tres-facile", label: "Tres facile" }] },

  // Section 15: Analyse Posturale (photos)
  { id: "photo-front", sectionId: "analyse-posturale", type: "photo", label: "Photo de FACE (debout, bras le long du corps)", required: true },
  { id: "photo-side", sectionId: "analyse-posturale", type: "photo", label: "Photo de PROFIL (cote droit, position naturelle)", required: true },
  { id: "photo-back", sectionId: "analyse-posturale", type: "photo", label: "Photo de DOS (debout, bras le long du corps)", required: true },
];

export const SECTIONS = [
  { id: "profil-base", title: "Profil de Base", icon: "User", description: "Informations generales sur toi" },
  { id: "composition-corporelle", title: "Composition Corporelle", icon: "Scale", description: "Analyse de ta composition" },
  { id: "metabolisme-energie", title: "Metabolisme & Energie", icon: "Zap", description: "Ton metabolisme et energie" },
  { id: "nutrition-tracking", title: "Nutrition & Tracking", icon: "Utensils", description: "Tes habitudes alimentaires" },
  { id: "digestion-microbiome", title: "Digestion & Microbiome", icon: "Activity", description: "Ta sante digestive" },
  { id: "activite-performance", title: "Activite & Performance", icon: "Dumbbell", description: "Ton activite physique" },
  { id: "sommeil-recuperation", title: "Sommeil & Recuperation", icon: "Moon", description: "La qualite de ton sommeil" },
  { id: "hrv-cardiaque", title: "HRV & Cardiaque", icon: "Heart", description: "Ta sante cardiaque" },
  { id: "analyses-biomarqueurs", title: "Analyses & Biomarqueurs", icon: "TestTube", description: "Tes analyses sanguines" },
  { id: "hormones-stress", title: "Hormones & Stress", icon: "Brain", description: "Ton equilibre hormonal" },
  { id: "lifestyle-substances", title: "Lifestyle & Substances", icon: "Coffee", description: "Ton mode de vie" },
  { id: "biomecanique-mobilite", title: "Biomecanique & Mobilite", icon: "Move", description: "Ta mobilite corporelle" },
  { id: "psychologie-mental", title: "Psychologie & Mental", icon: "HeartHandshake", description: "Ton equilibre psychologique" },
  { id: "neurotransmetteurs", title: "Neurotransmetteurs", icon: "Sparkles", description: "Ta sante cognitive" },
  { id: "analyse-posturale", title: "Analyse Posturale", icon: "Camera", description: "Photos pour analyse biomecanique" },
];

export function getQuestionsForSection(sectionId: string, userSex?: string) {
  return QUESTIONS.filter((q) => {
    if (q.sectionId !== sectionId) return false;
    if (!q.showFor || q.showFor === "all") return true;
    if (!userSex) return true;
    return q.showFor === userSex;
  });
}

export function getSectionProgress(
  sectionId: string,
  responses: Record<string, unknown>,
  userSex?: string
) {
  const sectionQuestions = getQuestionsForSection(sectionId, userSex);
  const answeredQuestions = sectionQuestions.filter(
    (q) => responses[q.id] !== undefined && responses[q.id] !== ""
  );
  return {
    total: sectionQuestions.length,
    answered: answeredQuestions.length,
    percentage: Math.round((answeredQuestions.length / sectionQuestions.length) * 100),
  };
}
