import { useMemo, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { ArrowLeft, ArrowRight, Check, Loader2, LockKeyhole, ShieldCheck, Sparkles } from "lucide-react";
import { trackClick, trackFormSubmit } from "@/lib/analytics";

type Goal = "recovery" | "gh-antiaging" | "fatloss" | "sleep" | "cognitive" | "libido" | "testo-boost" | "skin-hair" | "endurance";
type PreviewResult = {
  status: "eligible" | "review_required";
  moleculeCount: number;
  molecules: Array<{
    name: string; role: string; reason: string; doseSummary: string; administrationCount: number;
    startingFormat: string; startingPackagePriceUsd: number; cycleDurationLabel: string; calculationBasis: string; totalRequiredMg: number;
    vialStrengthMg: number; mathematicalVials: number; operationalVials: number; vialsRequired: number; vialsPurchased: number;
    packageCount: number; estimatedTotalPriceUsd: number;
  }>;
  estimatedProtocolCostUsd: number | null;
  estimatedShippingCostUsd: number | null;
  estimatedGrandTotalUsd: number | null;
  monthlyEquivalentUsd: number | null;
  shippingBreakdown: Array<{ supplier: string; subtotalUsd: number; shippingUsd: number; speed: string }>;
  totalVialsRequired: number | null; totalVialsPurchased: number | null; totalPackages: number | null;
  priceCheckedAt: string; durationLabel: string; budgetFit: "within" | "above" | "unknown"; headline: string; rationale: string;
  analysisPoints: string[]; requiredMarkers: string[]; nextStepExplanation: string;
  budgetExplanation: string; quoteExplanation: string; blockers: string[]; nextStep: "peptides_engine" | "blood_analysis" | "manual_review";
};

type FormState = {
  firstName: string; email: string; age: string; weightKg: string; heightCm: string; sex: "female" | "male"; bodyFatRange: string;
  primaryGoal: Goal | ""; secondaryGoals: Goal[]; goalDetails: string; timeline: "4-6" | "8-12" | "12plus";
  recoveryScope: "localized" | "multi-site" | "systemic" | "not-applicable";
  glp1History: "never" | "tolerated" | "stopped-side-effects" | "current" | "not-applicable";
  cognitiveStress: "low" | "moderate" | "high" | "not-applicable";
  conditions: string[]; bloodwork: "recent" | "old" | "never"; bloodPressure: "normal" | "controlled" | "high" | "unknown"; sleepHours: string;
  medications: string; allergies: string; experience: "none" | "read" | "tried" | "regular"; currentPeptides: string; pastPeptides: string;
  trainingFrequency: "none" | "1-2" | "3-4" | "5plus"; injectionComfort: "comfortable" | "possible" | "anxious" | "refuse";
  injectionFrequency: "twice-daily" | "daily" | "few-week" | "weekly" | "minimal"; refrigeration: "yes-private" | "yes-shared" | "no";
  budgetTotalUsd: string; country: string; startWhen: "asap" | "1-2weeks" | "1month" | "planning"; consent: boolean;
};

const goals: Array<{ value: Goal; label: string; detail: string }> = [
  { value: "fatloss", label: "Perte de graisse", detail: "Appétit, métabolisme, recomposition" },
  { value: "recovery", label: "Récupération", detail: "Tendons, articulations, blessure" },
  { value: "gh-antiaging", label: "Axe GH", detail: "Récupération, longévité, composition" },
  { value: "sleep", label: "Sommeil", detail: "Endormissement, réveils, profondeur" },
  { value: "cognitive", label: "Cognition", detail: "Focus, mémoire, stabilité sous stress" },
  { value: "endurance", label: "Endurance", detail: "Capacité de travail, mitochondries" },
  { value: "libido", label: "Libido", detail: "Réponse sexuelle et performance" },
  { value: "testo-boost", label: "Axe testostérone", detail: "Production endogène et fertilité" },
  { value: "skin-hair", label: "Peau et cheveux", detail: "Matrice, qualité cutanée, densité" },
];
const conditions = [
  ["none", "Aucune"], ["diabetes", "Diabète"], ["cancer", "Cancer actif ou antécédent"], ["pregnant", "Grossesse"],
  ["breastfeeding", "Allaitement"], ["autoimmune", "Maladie auto immune"], ["cardiac", "Problème cardiaque"],
  ["hypertension", "Hypertension"], ["thyroid", "Trouble thyroïdien"], ["renal-hepatic", "Atteinte rénale ou hépatique"],
] as const;
const countries = [["FR", "France"], ["BE", "Belgique"], ["CH", "Suisse"], ["LU", "Luxembourg"], ["AE", "Émirats arabes unis"], ["CA", "Canada"], ["US", "États Unis"], ["GB", "Royaume Uni"], ["DE", "Allemagne"], ["ES", "Espagne"], ["IT", "Italie"], ["NL", "Pays Bas"], ["PT", "Portugal"], ["MA", "Maroc"], ["DZ", "Algérie"], ["TN", "Tunisie"]] as const;
const initialForm: FormState = {
  firstName: "", email: "", age: "", weightKg: "", heightCm: "", sex: "male", bodyFatRange: "unknown",
  primaryGoal: "", secondaryGoals: [], goalDetails: "", timeline: "12plus", recoveryScope: "not-applicable", glp1History: "not-applicable", cognitiveStress: "not-applicable",
  conditions: ["none"], bloodwork: "never", bloodPressure: "unknown", sleepHours: "", medications: "", allergies: "",
  experience: "none", currentPeptides: "", pastPeptides: "", trainingFrequency: "3-4", injectionComfort: "possible",
  injectionFrequency: "few-week", refrigeration: "yes-private", budgetTotalUsd: "200", country: "FR", startWhen: "1-2weeks", consent: false,
};

function Choice({ active, title, detail, onClick }: { active: boolean; title: string; detail?: string; onClick: () => void }) {
  return <button type="button" aria-pressed={active} onClick={onClick} className={`w-full rounded-2xl border p-4 text-left transition ${active ? "border-amber-400 bg-amber-400/10 shadow-[0_0_0_1px_rgba(251,191,36,.2)]" : "border-white/10 bg-white/[.035] hover:border-white/25"}`}><span className="flex items-center gap-3"><span className={`flex h-5 w-5 shrink-0 items-center justify-center rounded-full border ${active ? "border-amber-400 bg-amber-400 text-black" : "border-white/30"}`}>{active && <Check className="h-3.5 w-3.5" />}</span><span><strong className="block text-sm text-white">{title}</strong>{detail && <span className="mt-1 block text-xs leading-relaxed text-zinc-400">{detail}</span>}</span></span></button>;
}
function Field({ label, children, full = false }: { label: string; children: React.ReactNode; full?: boolean }) {
  return <label className={full ? "block sm:col-span-2" : "block"}><span className="mb-2 block text-xs font-semibold uppercase tracking-[.16em] text-zinc-400">{label}</span>{children}</label>;
}
const inputClass = "w-full rounded-xl border border-white/10 bg-white/[.05] px-4 py-3.5 text-white outline-none transition placeholder:text-zinc-600 focus:border-amber-400";
const optionLabels: Record<string, string> = { female: "Femme", male: "Homme", recent: "Moins de 3 mois", old: "Plus de 3 mois", never: "Jamais", normal: "Normale", controlled: "Traitée et contrôlée", high: "Élevée", unknown: "Je ne sais pas", none: "Aucun", read: "Je me suis renseigné", tried: "Déjà utilisé", regular: "Utilisateur régulier", "twice-daily": "Jusqu’à deux fois par jour", daily: "Une fois par jour", "few-week": "Deux à cinq fois par semaine", weekly: "Une fois par semaine", minimal: "Le minimum possible", "yes-private": "Oui, frigo privé", "yes-shared": "Oui, frigo partagé", no: "Non", asap: "Dès que possible", "1-2weeks": "Dans une à deux semaines", "1month": "Dans un mois", planning: "Je prépare pour plus tard", "4-6": "Douze semaines minimum", "8-12": "Douze semaines minimum", "12plus": "Douze semaines minimum", localized: "Une zone précise", "multi-site": "Plusieurs zones", systemic: "Récupération générale", "not-applicable": "Non concerné", tolerated: "Déjà utilisé et bien toléré", "stopped-side-effects": "Arrêté pour effets indésirables", current: "En cours actuellement", low: "Faible", moderate: "Modéré", highStress: "Élevé", under10: "Moins de 10 %", "10-15": "10 à 15 %", "15-20": "15 à 20 %", "20-25": "20 à 25 %", "25-30": "25 à 30 %", over30: "Plus de 30 %" };

export default function PeptidesPreviewPage() {
  const [step, setStep] = useState(0); const [form, setForm] = useState<FormState>(initialForm); const [result, setResult] = useState<PreviewResult | null>(null); const [checkoutUrl, setCheckoutUrl] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const selectedPrimary = goals.find((goal) => goal.value === form.primaryGoal);
  const selectedGoals = form.primaryGoal ? [form.primaryGoal, ...form.secondaryGoals] : form.secondaryGoals;
  const canContinue = useMemo(() => {
    if (step === 0) return form.firstName.trim().length >= 2 && /^\S+@\S+\.\S+$/.test(form.email) && Number(form.age) >= 18 && Number(form.weightKg) >= 40 && Number(form.heightCm) >= 140;
    if (step === 1) return Boolean(form.primaryGoal) && form.goalDetails.trim().length >= 20 && (!selectedGoals.includes("recovery") || form.recoveryScope !== "not-applicable") && (!selectedGoals.includes("fatloss") || form.glp1History !== "not-applicable") && (!selectedGoals.includes("cognitive") || form.cognitiveStress !== "not-applicable");
    if (step === 2) return form.conditions.length > 0 && Number(form.sleepHours) >= 2 && form.medications.trim().length >= 2 && form.allergies.trim().length >= 2;
    if (step === 3) return form.currentPeptides.trim().length >= 2 && form.pastPeptides.trim().length >= 2;
    if (step === 4) return Number(form.budgetTotalUsd) >= 50;
    return form.consent;
  }, [form, selectedGoals, step]);
  const toggleSecondary = (value: Goal) => setForm((current) => current.primaryGoal === value ? current : { ...current, secondaryGoals: current.secondaryGoals.includes(value) ? current.secondaryGoals.filter((goal) => goal !== value) : [...current.secondaryGoals, value].slice(-2) });
  const selectPrimary = (value: Goal) => setForm((current) => {
    const secondaryGoals = current.secondaryGoals.filter((goal) => goal !== value);
    const nextGoals = [value, ...secondaryGoals];
    return {
      ...current,
      primaryGoal: value,
      secondaryGoals,
      recoveryScope: nextGoals.includes("recovery") ? current.recoveryScope : "not-applicable",
      glp1History: nextGoals.includes("fatloss") ? current.glp1History : "not-applicable",
      cognitiveStress: nextGoals.includes("cognitive") ? current.cognitiveStress : "not-applicable",
    };
  });
  const toggleCondition = (value: string) => setForm((current) => { if (value === "none") return { ...current, conditions: ["none"] }; const next = current.conditions.filter((item) => item !== "none"); const changed = next.includes(value) ? next.filter((item) => item !== value) : [...next, value]; return { ...current, conditions: changed.length ? changed : ["none"] }; });
  const submit = async () => {
    if (!canContinue || !form.primaryGoal) return; setLoading(true); setError("");
    try { const params = new URLSearchParams(window.location.search); const response = await fetch("/api/peptides-preview/analyze", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, age: Number(form.age), weightKg: Number(form.weightKg), heightCm: Number(form.heightCm), sleepHours: Number(form.sleepHours), budgetTotalUsd: Number(form.budgetTotalUsd), attribution: { source: params.get("utm_source") || undefined, medium: params.get("utm_medium") || undefined, campaign: params.get("utm_campaign") || undefined, content: params.get("utm_content") || undefined } }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.message || "Impossible de calculer ton aperçu maintenant."); setResult(payload.result); setCheckoutUrl(payload.checkoutUrl); trackFormSubmit("peptides_preview_completed"); trackClick(`peptides_preview_result_${payload.result.status}`); window.scrollTo({ top: 0, behavior: "smooth" }); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Erreur temporaire."); } finally { setLoading(false); }
  };

  if (result) return <main className="min-h-screen bg-[#08090b] px-4 py-10 text-white sm:px-6"><div className="mx-auto max-w-4xl"><div className="mb-8 flex items-center justify-between"><a href="/offers/peptides-engine" className="text-sm font-black tracking-[.22em]">APEX<span className="text-amber-400">LABS</span></a><span className={`rounded-full border px-3 py-1 text-xs ${result.status === "eligible" ? "border-emerald-400/25 bg-emerald-400/10 text-emerald-300" : "border-amber-400/25 bg-amber-400/10 text-amber-300"}`}>Estimation complète calculée</span></div><section className="overflow-hidden rounded-[28px] border border-white/10 bg-gradient-to-b from-white/[.075] to-white/[.025]"><div className="border-b border-white/10 p-6 sm:p-10"><p className="text-xs font-bold uppercase tracking-[.22em] text-amber-400">Pré calcul personnalisé de {form.firstName}</p><h1 className="mt-4 max-w-3xl text-3xl font-semibold leading-tight sm:text-5xl">{result.headline}</h1><p className="mt-4 max-w-3xl text-sm leading-7 text-zinc-400">{result.rationale}</p></div>
  <div className="border-b border-white/10 p-6 sm:p-10"><p className="text-xs font-bold uppercase tracking-[.18em] text-amber-400">Ce que ton profil change dans la décision</p><ul className="mt-4 space-y-3 text-sm leading-6 text-zinc-300">{result.analysisPoints.map((point, index) => <li key={index} className="flex gap-3"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-amber-400" />{point}</li>)}</ul></div>
  <div className="border-t border-white/10 bg-black/25 p-6 sm:p-10"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><Quote label="Nombre de molécules" value={String(result.moleculeCount)} /><Quote label="Durée estimée" value={result.durationLabel} /><Quote label="Produits" value={result.estimatedProtocolCostUsd == null ? "Dans Peptides Engine" : `$${result.estimatedProtocolCostUsd.toFixed(2)}`} /><Quote label="Livraison · une seule fois" value={result.estimatedShippingCostUsd == null ? "Dans Peptides Engine" : `$${result.estimatedShippingCostUsd.toFixed(2)}`} /><Quote label="Total rendu estimé" value={result.estimatedGrandTotalUsd == null ? "Dans Peptides Engine" : `$${result.estimatedGrandTotalUsd.toFixed(2)}`} emphasis /></div><div className="mt-4 rounded-xl border border-amber-400/20 bg-amber-400/[.07] px-4 py-3 text-sm leading-6 text-amber-100">Les noms des molécules et les dosages sont réservés à l’analyse complète. Le prix intègre une marge de 20 % dans la quantité totale pour limiter le risque de rachat en milieu de protocole, sans ajouter automatiquement une fiole entière par molécule. La livraison est comptée une seule fois pour la commande complète. Cette estimation peut évoluer après l’achat de Peptides Engine, lorsque le protocole plus poussé et plus précis sera construit selon ton profil.</div><div className="mt-4 rounded-2xl border border-white/10 bg-white/[.03] p-5"><span className="text-xs font-bold uppercase tracking-[.16em] text-zinc-400">Ce que Peptides Engine va construire</span><p className="mt-3 text-sm leading-6 text-zinc-200">{result.nextStepExplanation}</p></div><a href={checkoutUrl} onClick={() => trackClick("peptides_preview_unlock", checkoutUrl)} className="mt-6 flex w-full items-center justify-center gap-2 rounded-full bg-amber-400 px-6 py-4 text-center text-sm font-bold text-black transition hover:bg-amber-300">Débloquer mon analyse Peptides Engine<ArrowRight className="h-4 w-4" /></a><div className="mt-4 rounded-xl border border-emerald-400/20 bg-emerald-400/10 px-4 py-3 text-center text-xs text-emerald-300">Une copie détaillée est en cours d'envoi à {form.email}.</div><div className="mt-4 flex items-center justify-center gap-2 text-center text-xs text-zinc-600"><LockKeyhole className="h-3.5 w-3.5" />Peptides Engine personnalise la sélection, le calendrier, les quantités et la liste d’achat finale.</div></div></section></div></main>;

  const panels = [
    <div className="grid gap-5 sm:grid-cols-2" key="identity"><Field label="Prénom"><input className={inputClass} value={form.firstName} onChange={(e) => setForm({ ...form, firstName: e.target.value })} placeholder="Ton prénom" /></Field><Field label="Email"><input className={inputClass} type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} placeholder="ton@email.com" /></Field><Field label="Âge"><input className={inputClass} type="number" min="18" max="75" value={form.age} onChange={(e) => setForm({ ...form, age: e.target.value })} /></Field><Field label="Sexe"><select className={inputClass} value={form.sex} onChange={(e) => setForm({ ...form, sex: e.target.value as FormState["sex"] })}><option value="male">Homme</option><option value="female">Femme</option></select></Field><Field label="Poids actuel"><input className={inputClass} type="number" min="40" max="220" step="0.1" value={form.weightKg} onChange={(e) => setForm({ ...form, weightKg: e.target.value })} placeholder="82 kg" /></Field><Field label="Taille"><input className={inputClass} type="number" min="140" max="220" value={form.heightCm} onChange={(e) => setForm({ ...form, heightCm: e.target.value })} placeholder="182 cm" /></Field><Field label="Masse grasse estimée" full><select className={inputClass} value={form.bodyFatRange} onChange={(e) => setForm({ ...form, bodyFatRange: e.target.value })}>{["unknown", "under10", "10-15", "15-20", "20-25", "25-30", "over30"].map((value) => <option value={value} key={value}>{optionLabels[value]}</option>)}</select></Field></div>,
    <div key="goals"><p className="mb-3 text-sm text-zinc-400">Choisis la priorité qui doit piloter les molécules, le dosage de référence et le devis.</p><div className="grid gap-3 sm:grid-cols-2">{goals.map((goal) => <Choice key={goal.value} active={form.primaryGoal === goal.value} title={goal.label} detail={goal.detail} onClick={() => selectPrimary(goal.value)} />)}</div>{form.primaryGoal && <><div className="mt-6 flex flex-wrap gap-2">{goals.filter((goal) => goal.value !== form.primaryGoal).map((goal) => <button key={goal.value} type="button" onClick={() => toggleSecondary(goal.value)} className={`rounded-full border px-3 py-2 text-xs ${form.secondaryGoals.includes(goal.value) ? "border-amber-400 bg-amber-400/10 text-amber-300" : "border-white/10 text-zinc-400"}`}>{goal.label}</button>)}</div><div className="mt-6 grid gap-5 sm:grid-cols-2"><Field label="Horizon de résultat souhaité"><select className={inputClass} value={form.timeline} onChange={(e) => setForm({ ...form, timeline: e.target.value as FormState["timeline"] })}>{["12plus"].map((value) => <option key={value} value={value}>{optionLabels[value]}</option>)}</select></Field>{selectedGoals.includes("recovery") && <Field label="Étendue"><select className={inputClass} value={form.recoveryScope} onChange={(e) => setForm({ ...form, recoveryScope: e.target.value as FormState["recoveryScope"] })}><option value="not-applicable">Choisir</option><option value="localized">Une zone précise</option><option value="multi-site">Plusieurs zones</option><option value="systemic">Récupération générale</option></select></Field>}{selectedGoals.includes("fatloss") && <Field label="Historique GLP 1"><select className={inputClass} value={form.glp1History} onChange={(e) => setForm({ ...form, glp1History: e.target.value as FormState["glp1History"] })}><option value="not-applicable">Choisir</option><option value="never">Jamais utilisé</option><option value="tolerated">Déjà utilisé et bien toléré</option><option value="stopped-side-effects">Arrêté pour effets indésirables</option><option value="current">En cours actuellement</option></select></Field>}{selectedGoals.includes("cognitive") && <Field label="Stress cognitif"><select className={inputClass} value={form.cognitiveStress} onChange={(e) => setForm({ ...form, cognitiveStress: e.target.value as FormState["cognitiveStress"] })}><option value="low">Faible</option><option value="moderate">Modéré</option><option value="high">Élevé</option></select></Field>}<Field label="Situation, historique, résultat attendu" full><textarea className={`${inputClass} min-h-32`} value={form.goalDetails} onChange={(e) => setForm({ ...form, goalDetails: e.target.value })} placeholder="Décris le problème, depuis quand, ce que tu as déjà essayé, ce qui a fonctionné ou échoué et le résultat précis attendu." /></Field></div></>}</div>,
    <div key="health"><p className="mb-4 text-sm leading-6 text-zinc-400">Ces réponses permettent à Peptides Engine de personnaliser la sélection, le calendrier et les quantités autour de ton profil.</p><div className="grid gap-3 sm:grid-cols-2">{conditions.map(([value, label]) => <Choice key={value} active={form.conditions.includes(value)} title={label} onClick={() => toggleCondition(value)} />)}</div><div className="mt-6 grid gap-5 sm:grid-cols-2"><Field label="Bilan sanguin"><select className={inputClass} value={form.bloodwork} onChange={(e) => setForm({ ...form, bloodwork: e.target.value as FormState["bloodwork"] })}>{["recent", "old", "never"].map((value) => <option key={value} value={value}>{optionLabels[value]}</option>)}</select></Field><Field label="Tension artérielle"><select className={inputClass} value={form.bloodPressure} onChange={(e) => setForm({ ...form, bloodPressure: e.target.value as FormState["bloodPressure"] })}>{["normal", "controlled", "high", "unknown"].map((value) => <option key={value} value={value}>{optionLabels[value]}</option>)}</select></Field><Field label="Sommeil moyen"><input className={inputClass} type="number" min="2" max="12" step="0.5" value={form.sleepHours} onChange={(e) => setForm({ ...form, sleepHours: e.target.value })} placeholder="7 heures" /></Field><Field label="Médicaments actuels"><input className={inputClass} value={form.medications} onChange={(e) => setForm({ ...form, medications: e.target.value })} placeholder="Aucun, ou noms et doses" /></Field><Field label="Allergies" full><input className={inputClass} value={form.allergies} onChange={(e) => setForm({ ...form, allergies: e.target.value })} placeholder="Aucune, ou liste exacte" /></Field></div></div>,
    <div className="grid gap-5 sm:grid-cols-2" key="history"><Field label="Expérience peptides"><select className={inputClass} value={form.experience} onChange={(e) => setForm({ ...form, experience: e.target.value as FormState["experience"] })}>{["none", "read", "tried", "regular"].map((value) => <option key={value} value={value}>{optionLabels[value]}</option>)}</select></Field><Field label="Entraînements par semaine"><select className={inputClass} value={form.trainingFrequency} onChange={(e) => setForm({ ...form, trainingFrequency: e.target.value as FormState["trainingFrequency"] })}><option value="none">Aucun</option><option value="1-2">Une à deux</option><option value="3-4">Trois à quatre</option><option value="5plus">Cinq ou plus</option></select></Field><Field label="Peptides actuels" full><textarea className={`${inputClass} min-h-24`} value={form.currentPeptides} onChange={(e) => setForm({ ...form, currentPeptides: e.target.value })} placeholder="Aucun, ou molécule, dose, fréquence et depuis quand" /></Field><Field label="Peptides passés et résultats" full><textarea className={`${inputClass} min-h-24`} value={form.pastPeptides} onChange={(e) => setForm({ ...form, pastPeptides: e.target.value })} placeholder="Aucun, ou molécule, dose, durée, résultat et raison d'arrêt" /></Field></div>,
    <div className="grid gap-5 sm:grid-cols-2" key="constraints"><Field label="Confort injections"><select className={inputClass} value={form.injectionComfort} onChange={(e) => setForm({ ...form, injectionComfort: e.target.value as FormState["injectionComfort"] })}><option value="comfortable">À l'aise</option><option value="possible">Possible si nécessaire</option><option value="anxious">Anxieux mais ouvert</option><option value="refuse">Je refuse</option></select></Field><Field label="Fréquence acceptable"><select className={inputClass} value={form.injectionFrequency} onChange={(e) => setForm({ ...form, injectionFrequency: e.target.value as FormState["injectionFrequency"] })}>{["twice-daily", "daily", "few-week", "weekly", "minimal"].map((value) => <option key={value} value={value}>{optionLabels[value]}</option>)}</select></Field><Field label="Stockage au froid"><select className={inputClass} value={form.refrigeration} onChange={(e) => setForm({ ...form, refrigeration: e.target.value as FormState["refrigeration"] })}>{["yes-private", "yes-shared", "no"].map((value) => <option key={value} value={value}>{optionLabels[value]}</option>)}</select></Field><Field label="Budget total du cycle en USD"><input className={inputClass} type="number" min="50" max="5000" step="10" value={form.budgetTotalUsd} onChange={(e) => setForm({ ...form, budgetTotalUsd: e.target.value })} /></Field><Field label="Pays"><select className={inputClass} value={form.country} onChange={(e) => setForm({ ...form, country: e.target.value })}>{countries.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field><Field label="Début souhaité"><select className={inputClass} value={form.startWhen} onChange={(e) => setForm({ ...form, startWhen: e.target.value as FormState["startWhen"] })}>{["asap", "1-2weeks", "1month", "planning"].map((value) => <option key={value} value={value}>{optionLabels[value]}</option>)}</select></Field></div>,
    <div key="confirm"><div className="rounded-2xl border border-white/10 bg-black/20 p-5 text-sm leading-7 text-zinc-300"><strong className="text-white">Vérifie avant calcul</strong><p className="mt-2">Objectif : {selectedPrimary?.label}. Profil : {form.age} ans, {form.weightKg} kg, {form.heightCm} cm. Budget total : ${form.budgetTotalUsd}. Pays : {countries.find(([value]) => value === form.country)?.[1]}.</p><p className="mt-2 text-zinc-500">Le moteur calcule en interne 2 à 4 molécules sur 12 semaines minimum : dosage, besoin total, nombre de fioles, boîtes, prix des produits, livraison vers le pays choisi et total rendu estimé.</p></div><label className="mt-5 flex cursor-pointer items-start gap-3 rounded-2xl border border-white/10 bg-white/[.03] p-4"><input type="checkbox" className="mt-1 h-4 w-4 accent-amber-400" checked={form.consent} onChange={(e) => setForm({ ...form, consent: e.target.checked })} /><span className="text-xs leading-5 text-zinc-400">J'accepte que mes réponses et mon email soient enregistrés pour générer cet aperçu et recevoir les informations liées à Peptides Engine. Je peux demander leur suppression à tout moment.</span></label></div>,
  ];
  const titles = ["Ton profil mesurable", "Ce qui doit réellement guider le scénario", "Paramètres de personnalisation", "Historique et réponse passée", "Logistique et budget total", "Ton devis personnalisé"];
  return <main className="min-h-screen bg-[#08090b] px-4 py-8 text-white sm:px-6 sm:py-12"><div className="mx-auto max-w-3xl"><header className="mb-8 flex items-center justify-between"><a href="/offers/peptides-engine" className="text-sm font-black tracking-[.22em]">APEX<span className="text-amber-400">LABS</span></a><div className="flex items-center gap-2 text-xs text-zinc-500"><ShieldCheck className="h-4 w-4 text-emerald-400" />Calcul transparent</div></header><div className="mb-8"><div className="flex items-center justify-between text-xs text-zinc-500"><span>Étape {step + 1} sur 6</span><span>{Math.round(((step + 1) / 6) * 100)}%</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-white/10"><motion.div animate={{ width: `${((step + 1) / 6) * 100}%` }} className="h-full rounded-full bg-amber-400" /></div></div><section className="rounded-[28px] border border-white/10 bg-white/[.04] p-5 sm:p-9"><div className="mb-7"><div className="mb-4 flex h-11 w-11 items-center justify-center rounded-2xl bg-amber-400/10 text-amber-400"><Sparkles className="h-5 w-5" /></div><p className="text-xs font-bold uppercase tracking-[.2em] text-amber-400">Pré Peptides Engine</p><h1 className="mt-2 text-2xl font-semibold sm:text-4xl">{titles[step]}</h1></div><AnimatePresence mode="wait"><motion.div key={step} initial={{ opacity: 0, x: 18 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -18 }}>{panels[step]}</motion.div></AnimatePresence>{error && <p role="alert" className="mt-5 rounded-xl border border-red-400/30 bg-red-400/10 p-3 text-sm text-red-200">{error}</p>}<div className="mt-8 flex gap-3">{step > 0 && <button type="button" onClick={() => setStep(step - 1)} className="flex items-center gap-2 rounded-full border border-white/15 px-5 py-3 text-sm text-zinc-300"><ArrowLeft className="h-4 w-4" />Retour</button>}<button type="button" disabled={!canContinue || loading} onClick={() => step < 5 ? (step === 0 ? (trackClick("peptides_preview_started"), setStep(step + 1)) : setStep(step + 1)) : submit()} className="ml-auto flex items-center gap-2 rounded-full bg-amber-400 px-6 py-3 text-sm font-bold text-black disabled:cursor-not-allowed disabled:opacity-40">{loading ? <><Loader2 className="h-4 w-4 animate-spin" />Calcul du devis complet</> : step < 5 ? <>Continuer<ArrowRight className="h-4 w-4" /></> : <>Calculer mon devis<ArrowRight className="h-4 w-4" /></>}</button></div></section><p className="mt-5 text-center text-xs leading-5 text-zinc-600">Le moteur chiffre 2 à 4 molécules sur 12 semaines minimum, puis calcule les fioles, les boîtes, la livraison selon le pays et le total rendu. Peptides Engine affine ensuite le protocole complet.</p></div></main>;
}

function Quote({ label, value, emphasis = false }: { label: string; value: string; emphasis?: boolean }) {
  return <div className={`rounded-2xl border p-5 ${emphasis ? "border-amber-400/40 bg-amber-400/10" : "border-white/10"}`}><span className="text-xs uppercase tracking-wider text-zinc-500">{label}</span><strong className={`mt-2 block ${emphasis ? "text-2xl text-amber-300" : "text-xl text-white"}`}>{value}</strong></div>;
}
