export const TEST_CLIENT_DATA = {
  prenom: "Achkan",
  nom: "K.",
  email: "test@neurocore.fr",
  sexe: "homme",
  age: "26-35",
  taille: "178",
  poids: "82",
  objectifPrincipal: "recomposition",
  objectifSante: "energie",
  objectifPoids: "maintien",
  objectifPerformance: "force",
  delaiObjectif: "3-6 mois",
  attentesAudit: "Comprendre pourquoi je stagne malgre mes efforts et avoir un plan personnalise",
  niveauActivite: "intermediaire",
  frequenceEntrainement: "4-5",
  typeEntrainement: ["musculation", "cardio"],
  dureeSeance: "60-90",
  experienceAnnees: "3-5",
  equipementDisponible: ["salle de sport"],
  blessuresPassees: ["entorse cheville"],
  motivationSport: "haute",
  dureeSommeil: "6-7",
  qualiteSommeil: "moyenne",
  reveilsNocturnes: "1-2",
  fatigueMatin: "oui",
  difficulteEndormissement: "parfois",
  niveauStress: "eleve",
  sourceStress: ["travail", "finances"],
  gestionStress: "moyenne",
  anxiete: "occasionnelle",
  concentrationTravail: "moyenne",
  regimeAlimentaire: "omnivore",
  repasParJour: "3",
  hydratation: "1.5-2L",
  supplementsActuels: ["whey", "creatine", "vitamines"],
  budgetSupplements: "50-100",
  allergiesAlimentaires: [],
  intoleancesConnues: [],
  frequenceSelles: "quotidien",
  problemesDigestifs: ["ballonnements"],
  consommationAlcool: "occasionnel",
  consommationCafe: "2-3",
  travailType: "bureau sedentaire",
  heuresTravail: "8-10",
  pausesActives: "rarement",
  energieJournee: "variable",
  douleursChroniques: ["dos", "nuque"],
  problemesPosturaux: "oui",
  hormonesBilan: "jamais fait",
  libido: "moyenne",
  antecedentsFamiliaux: ["diabete", "hypertension"],
  medicaments: [],
  bilansRecents: [],
  tempsDisponible: "1-2h par jour",
  autresInfos: "Je me sens souvent fatigue meme apres une bonne nuit de sommeil"
};

export const TEST_PHOTO_URLS = {
  front: "server/test-data/photos/front.jpeg",
  back: "server/test-data/photos/back.jpeg",
  side: "server/test-data/photos/side.jpeg"
};
